In [1]:
import pandas as pd

In [35]:
df_1 = pd.read_csv("experiments_results/2024-05-17/17_13_20_chat_blocksworld_2000_4_blocks_balanced_1_T_0_mixtral.csv")
df_2 = pd.read_csv("experiments_results/2024-05-17/17_16_37_chat_blocksworld_2000_4_blocks_balanced_1_T_0_mixtral.csv")

In [36]:
df = pd.concat([df_1, df_2])

In [38]:
df.isna().sum()

instance_id               0
ground_truth_plan         0
goal_achieved             0
content                   0
actions_text              0
actions_possible          0
n_actions                 0
ground_truth_n_actions    0
dtype: int64

In [39]:
df.to_csv("experiments_results/2024-05-17/17_16_38_chat_blocksworld_2000_4_blocks_balanced_1_T_0_mixtral.csv")

In [12]:
df_1[df_1["actions_possible"].isna()] = df_2

In [25]:
df_1

,instance_id,ground_truth_plan,goal_achieved,content,actions_text,actions_possible,n_actions,ground_truth_n_actions
0,1657,(unstack b a)\n(put-down b)\n(unstack a c)\n(s...,False,human: I am playing with a set of blocks where...,unstack the blue block from on top of the red ...,1.1.0,3,10
1,1819,(unstack d c)\n(put-down d)\n(unstack c a)\n(p...,False,human: I am playing with a set of blocks where...,unstack the yellow block from on top of the or...,1.1.0.0.0.1.1.1.1.0.1.1.0.0.0.1,16,12
2,831,(unstack b d)\n(stack b a)\n,True,human: I am playing with a set of blocks where...,unstack the blue block from on top of the yell...,1.1.1.1,4,2
3,1280,(unstack d a)\n(stack d c)\n(unstack a b)\n(pu...,False,human: I am playing with a set of blocks where...,unstack the yellow block from on top of the re...,1.1.0,3,10
4,1451,(pick-up d)\n(stack d b)\n,False,human: I am playing with a set of blocks where...,pick up the yellow block.put down the yellow b...,1.1.0,3,2
...,...,...,...,...,...,...,...,...
763,956,(unstack c d)\n(put-down c)\n(unstack d b)\n(p...,False,human: I am playing with a set of blocks where...,unstack the blue block from on top of the red ...,0.1.1.0.0.0.0.0.0.1.0.1.0.0.0,15,6
764,876,(unstack a b)\n(put-down a)\n(unstack b d)\n(p...,False,human: I am playing with a set of blocks where...,unstack the blue block from on top of the yell...,0,1,12
765,1093,(unstack b d)\n(put-down b)\n(unstack d c)\n(p...,False,human: I am playing with a set of blocks where...,unstack the blue block from on top of the yell...,1.1.0,3,8
766,1830,(pick-up a)\n(stack a c)\n,False,human: I am playing with a set of blocks where...,pick up the red block.put down the red block.u...,1.1.0,3,2
767,1730,(unstack b a)\n(put-down b)\n(unstack a c)\n(p...,False,human: I am playing with a set of blocks where...,unstack the blue block from on top of the red ...,1.1.1.0.1.0.1.0.1.0.0.0.0.1.1.0,16,12

In [20]:
df_1[df_1["actions_possible"].isna()]

,instance_id,ground_truth_plan,goal_achieved,content,actions_text,actions_possible,n_actions,ground_truth_n_actions
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN